apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-dns
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dnstcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dnsudp
  externalIPs:
  - {{ .Values.ipaddress }}
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
