apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-dns
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dnstcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dnsudp
    - port: 853
      targetPort: 853
      protocol: TCP
      name: dnstls
  externalIPs:
  {{- range .Values.ipaddress }}
  - {{ . }}
  {{- end }}
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
