apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-web
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv6
  - IPv4
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
